baseURL = "https://cymosoft.com/"
languageCode = "en-us"
title = "Cymosoft | A Software Solution Company"
theme = "airspace-hugo"

################################# Basic configuration #########################
# Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# Number of posts per page in list view
paginate = "4"
# Post excerpt length
summaryLength = "30"
# Disabled languages
disableLanguages = []
# Short name to enable Disqus comments
disqusShortname = "" # Get your shortname from here: https://disqus.com/profile/signup/
# Measurement ID (G-XXXXXXX) to enable Google Analytics
googleAnalytics = ""


################################# Output formats ##############################
# Documentation: https://gohugo.io/templates/output-formats/#customizing-output-formats

[outputs]
home = [ "HTML" ]


################################# Markup ######################################
# Documentation: https://gohugo.io/getting-started/configuration-markup

[markup.goldmark.renderer]
# Allow "unsafe" HTML in Markdown
unsafe = true

[markup.tableOfContents]
  startLevel = 2
  endLevel = 6
  ordered = false


################################# Default parameters ##########################
[params]
favicon = "images/favicon.png"
logo = "images/logo.png"
logo_width = "150px"
# OpenGraph / Twitter Card metadata
title = "Cymosoft"
description = "This is meta description"
author = "Cymosoft"
images = [ "images/logo.png" ] # First image here will be used as fallback if a page has no images of its own


################################# Sidebar widgets #############################
[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]


################################# Contact page ################################
[params.contact]
# Address block
phone = "098-1234-5678"
email = "contact@cymosoft.com"
location = "Hanoi, Vietnam"
# Whether to display text descriptors (like "E-mail: ", "Phone: ") before the address block elements
address_descriptors = true
[params.contact.form]
enable = true
# Whether to use [Netlify Forms](https://docs.netlify.com/forms/setup/)
use_netlify = false
# Form action
## For Formspree.io: Your Form ID URL, e.g. `https://formspree.io/f/{form_id}`
## For Netlify Forms: Path to a custom [success page](https://docs.netlify.com/forms/setup/#success-messages)
action = "#"


################################# Google map ##################################
[params.gmap]
enable = true
gmap_api = "AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"


################################# Preloader ###################################
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif image


################################# Cookies #####################################
[params.cookies]
enable = true
expire_days = 2


################################# Social Media ################################
[[params.social]]
icon = "ion-social-googleplus-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-linkedin-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-pinterest-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-dribbble-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-twitter-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://twitter.com/cymosoft"

[[params.social]]
icon = "ion-social-facebook-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"


################################# Plugins #####################################
# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/css/bootstrap.min.css"
attributes = "media='screen'"

[[params.plugins.css]]
link = "plugins/ionicons/css/ionicons.min.css"
attributes = ""

[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.min.css"
attributes = ""

[[params.plugins.css]]
link = "plugins/slick/slick.css"
attributes = ""

# JS Plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/bootstrap/js/bootstrap.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/magnific-popup/magnific-popup.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
attributes = "defer"


################################# English translation #########################
[languages.en]
languageName = "English"
languageCode = "en-US"
contentDir = "content/english"
weight = 1
copyright = "Copyright &copy; 2021 [Cymosoft](https://cymosoft.com). All Rights Reserved."

# Main menu
[[languages.en.menu.main]]
name = "Home"
URL = "/"
weight = 1

[[languages.en.menu.main]]
name = "About"
URL = "about"
weight = 2

[[languages.en.menu.main]]
name = "Project"
URL = "project"
weight = 3

[[languages.en.menu.main]]
name = "Blog"
URL = "blog"
weight = 4

[[languages.en.menu.main]]
weight = 5
name = "More"
hasChildren = true

  [[languages.en.menu.main]]
  parent = "More"
  name = "FAQ"
  URL = "faq"

  [[languages.en.menu.main]]
  parent = "More"
  name = "Pricing"
  URL = "pricing"

  [[languages.en.menu.main]]
  parent = "More"
  name = "Service"
  URL = "service"

[[languages.en.menu.main]]
name = "Contact"
URL = "contact"
weight = 6

# Footer menu
[[languages.en.menu.footer]]
name = "About"
URL = "about"
weight = 1

[[languages.en.menu.footer]]
name = "Project"
URL = "project"
weight = 2

[[languages.en.menu.footer]]
name = "Service"
URL = "service"
weight = 3

[[languages.en.menu.footer]]
name = "Pricing"
URL = "pricing"
weight = 4

[[languages.en.menu.footer]]
name = "FAQ"
URL = "faq"
weight = 5

[[languages.en.menu.footer]]
name = "Contact"
URL = "contact"
weight = 6


################################# French translation ##########################
[languages.ja]
languageName = "日本語"
languageCode = "ja-JP"
contentDir = "content/japanese"
weight = 2
copyright = "Copyright &copy; 2021 [Cymosoft](https://themefisher.com). Tous droits réservés."

# Main menu
[[languages.ja.menu.main]]
name = "ホーム"
URL = "/"
weight = 1

[[languages.ja.menu.main]]
name = "会社情報"
URL = "about"
weight = 2

[[languages.ja.menu.main]]
name = "プロジェクト"
URL = "project"
weight = 3

[[languages.ja.menu.main]]
name = "ブログ"
URL = "blog"
weight = 4

[[languages.ja.menu.main]]
weight = 5
name = "もっと見る"
hasChildren = true

  [[languages.ja.menu.main]]
  parent = "もっと見る"
  name = "FAQ"
  URL = "faq"

  [[languages.ja.menu.main]]
  parent = "もっと見る"
  name = "価格"
  URL = "pricing"

  [[languages.ja.menu.main]]
  parent = "もっと見る"
  name = "サービス"
  URL = "service"

[[languages.ja.menu.main]]
name = "お問い合わせ"
URL = "contact"
weight = 6

# Footer menu
[[languages.ja.menu.footer]]
name = "会社情報"
URL = "about"
weight = 1

[[languages.ja.menu.footer]]
name = "プロジェクト"
URL = "project"
weight = 2

[[languages.ja.menu.footer]]
name = "サービス"
URL = "service"
weight = 3

[[languages.ja.menu.footer]]
name = "価格"
URL = "pricing"
weight = 4

[[languages.ja.menu.footer]]
name = "FAQ"
URL = "faq"
weight = 5

[[languages.ja.menu.footer]]
name = "お問い合わせ"
URL = "contact"
weight = 6

################################# German translation ##########################
[languages.vi]
languageName = "Tiếng Việt"
languageCode = "vi-VN"
contentDir = "content/vietnamese"
weight = 3
copyright = "Copyright &copy; 2021 [Cymosoft](https://cymosoft.com). All rights reserved."

# Main menu
[[languages.vi.menu.main]]
name = "Trang chủ"
URL = "/"
weight = 1

[[languages.vi.menu.main]]
name = "Về chúng tôi"
URL = "about"
weight = 2

[[languages.vi.menu.main]]
name = "Dự án"
URL = "project"
weight = 3

[[languages.vi.menu.main]]
name = "Blog"
URL = "blog"
weight = 4

[[languages.vi.menu.main]]
name = "Thêm"
hasChildren = true
weight = 5

  [[languages.vi.menu.main]]
  parent = "Thêm"
  name = "FAQ"
  URL = "faq"

  [[languages.vi.menu.main]]
  parent = "Thêm"
  name = "Giá"
  URL = "pricing"

  [[languages.vi.menu.main]]
  parent = "Thêm"
  name = "Dịch vụ"
  URL = "service"

[[languages.vi.menu.main]]
name = "Liên lạc"
URL = "contact"
weight = 6

# Footer menu
[[languages.vi.menu.footer]]
name = "Về chúng tôi"
URL = "about"
weight = 1

[[languages.vi.menu.footer]]
name = "Dự án"
URL = "project"
weight = 2

[[languages.vi.menu.footer]]
name = "Dịch vụ"
URL = "service"
weight = 3

[[languages.vi.menu.footer]]
name = "Giá"
URL = "pricing"
weight = 4

[[languages.vi.menu.footer]]
name = "FAQ"
URL = "faq"
weight = 5

[[languages.vi.menu.footer]]
name = "Liên lạc"
URL = "contact"
weight = 6