baseURL = "https://cymosoft.com/"
disableLanguages = ["vi", "ja"]
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
paginate = "4"
summaryLength = "30"
theme = "airspace-hugo"
title = "Cymosoft | A Software Solution Company"
[languages.en]
contentDir = "content/english"
copyright = "&copy; [Cymosoft](https://cymosoft.com) 2022"
languageCode = "en-US"
languageName = "English"
weight = 1
[[languages.en.menu.footer]]
URL = "about"
name = "About"
weight = 1
[[languages.en.menu.footer]]
URL = "service"
name = "Service"
weight = 3
[[languages.en.menu.footer]]
URL = "contact"
name = "Contact"
weight = 6
[[languages.en.menu.main]]
URL = "/"
name = "Home"
weight = 1
[[languages.en.menu.main]]
URL = "about"
name = "About"
weight = 2
[[languages.en.menu.main]]
hasChildren = true
name = "More"
weight = 5
[[languages.en.menu.main]]
URL = "service"
name = "Service"
parent = "More"
[[languages.en.menu.main]]
URL = "contact"
name = "Contact"
weight = 6
[languages.ja]
contentDir = "content/japanese"
copyright = "&copy; [Cymosoft](https://cymosoft.com) 2022"
languageCode = "ja-JP"
languageName = "日本語"
weight = "2"
[[languages.ja.menu.footer]]
URL = "about"
name = "会社情報"
weight = 1
[[languages.ja.menu.footer]]
URL = "project"
name = "プロジェクト"
weight = 2
[[languages.ja.menu.footer]]
URL = "service"
name = "サービス"
weight = 3
[[languages.ja.menu.footer]]
URL = "pricing"
name = "価格"
weight = 4
[[languages.ja.menu.footer]]
URL = "faq"
name = "FAQ"
weight = 5
[[languages.ja.menu.footer]]
URL = "contact"
name = "お問い合わせ"
weight = 6
[[languages.ja.menu.main]]
URL = "/"
name = "ホーム"
weight = 1
[[languages.ja.menu.main]]
URL = "about"
name = "会社情報"
weight = 2
[[languages.ja.menu.main]]
URL = "project"
name = "プロジェクト"
weight = 3
[[languages.ja.menu.main]]
URL = "blog"
name = "ブログ"
weight = 4
[[languages.ja.menu.main]]
hasChildren = true
name = "もっと見る"
weight = 5
[[languages.ja.menu.main]]
URL = "faq"
name = "FAQ"
parent = "もっと見る"
[[languages.ja.menu.main]]
URL = "pricing"
name = "価格"
parent = "もっと見る"
[[languages.ja.menu.main]]
URL = "service"
name = "サービス"
parent = "もっと見る"
[[languages.ja.menu.main]]
URL = "contact"
name = "お問い合わせ"
weight = 6
[languages.vi]
contentDir = "content/vietnamese"
copyright = "&copy; [Cymosoft](https://cymosoft.com) 2022"
languageCode = "vi-VN"
languageName = "Tiếng Việt"
weight = 3
[[languages.vi.menu.footer]]
URL = "about"
name = "Về chúng tôi"
weight = 1
[[languages.vi.menu.footer]]
URL = "project"
name = "Dự án"
weight = 2
[[languages.vi.menu.footer]]
URL = "service"
name = "Dịch vụ"
weight = 3
[[languages.vi.menu.footer]]
URL = "pricing"
name = "Giá"
weight = 4
[[languages.vi.menu.footer]]
URL = "faq"
name = "FAQ"
weight = 5
[[languages.vi.menu.footer]]
URL = "contact"
name = "Liên lạc"
weight = 6
[[languages.vi.menu.main]]
URL = "/"
name = "Trang chủ"
weight = 1
[[languages.vi.menu.main]]
URL = "about"
name = "Về chúng tôi"
weight = 2
[[languages.vi.menu.main]]
URL = "project"
name = "Dự án"
weight = 3
[[languages.vi.menu.main]]
URL = "blog"
name = "Blog"
weight = 4
[[languages.vi.menu.main]]
hasChildren = true
name = "Thêm"
weight = 5
[[languages.vi.menu.main]]
URL = "faq"
name = "FAQ"
parent = "Thêm"
[[languages.vi.menu.main]]
URL = "pricing"
name = "Giá"
parent = "Thêm"
[[languages.vi.menu.main]]
URL = "service"
name = "Dịch vụ"
parent = "Thêm"
[[languages.vi.menu.main]]
URL = "contact"
name = "Liên lạc"
weight = 6
[markup.goldmark.renderer]
unsafe = true
[markup.tableOfContents]
endLevel = 6
ordered = false
startLevel = 2
[outputs]
home = ["HTML"]
[params]
author = "Cymosoft"
description = "Cymosoft - A software company"
favicon = "images/favicon.png"
images = ["images/logo.png"]
logo = "images/logo.png"
logo_width = "150px"
title = "Cymosoft"
[params.contact]
address_descriptors = true
email = "contact [at] cymosoft.com"
location = "A6-TT2 Van Quan Urban Area, Hadong District, Hanoi, Vietnam"
phone = "(+84) 0388827518"
[params.contact.form]
action = "#"
enable = true
use_netlify = false
[params.cookies]
enable = false
expire_days = 2
[params.gmap]
enable = false
gmap_api = "AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[[params.plugins.css]]
attributes = "media='screen'"
link = "plugins/bootstrap/css/bootstrap.min.css"
[[params.plugins.css]]
attributes = ""
link = "plugins/ionicons/css/ionicons.min.css"
[[params.plugins.css]]
attributes = ""
link = "plugins/magnific-popup/magnific-popup.min.css"
[[params.plugins.css]]
attributes = ""
link = "plugins/slick/slick.css"
[[params.plugins.js]]
attributes = ""
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
attributes = ""
link = "plugins/bootstrap/js/bootstrap.min.js"
[[params.plugins.js]]
attributes = ""
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
attributes = ""
link = "plugins/magnific-popup/magnific-popup.min.js"
[[params.plugins.js]]
attributes = ""
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
attributes = "defer"
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = true
preloader = ""
[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]
[[params.social]]
icon = "ion-social-linkedin-outline"
link = "#"
[[params.social]]
icon = "ion-social-twitter-outline"
link = "https://twitter.com/cymosoft"
[[params.social]]
icon = "ion-social-facebook-outline"
link = "#"
